apiVersion: v1
kind: Secret
metadata:
  name: jfrogcred
  namespace: valaxy
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJ0aGFuaGxjMy5qZnJvZy5pbyI6IHsKCQkJImF1dGgiOiAiZEdoaGJtaHNZek02VW1WdGIzUmxLRzl1ZEhKdmJESXpPQ2s9IgoJCX0KCX0KfQ==
type: kubernetes.io/dockerconfigjson